---
acc_cluster:
  - Name: mttkrp_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/sys_validation/mttkrp/hw/top.ll
      ConfigPath: benchmarks/sys_validation/mttkrp/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: mttkrp
      IrPath: benchmarks/sys_validation/mttkrp/hw/mttkrp.ll
      ConfigPath: benchmarks/sys_validation/mttkrp/hw/mttkrp.ini
      Debug: False
      PIOSize: 10
      PIOMaster: LocalBus