---
acc_cluster:
  - Name: bilateral_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/sys_validation/bilateral/hw/top.ll
      ConfigPath: benchmarks/sys_validation/bilateral/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: bilateral
      IrPath: benchmarks/sys_validation/bilateral/hw/bilateral.ll
      ConfigPath: benchmarks/sys_validation/bilateral/hw/bilateral.ini
      Debug: False
      PIOSize: 10
      PIOMaster: LocalBus