---
acc_cluster:
  - Name: sddmm_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/AD/sddmm/hw/top.ll
      ConfigPath: benchmarks/AD/sddmm/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: sddmm
      IrPath: benchmarks/AD/sddmm/hw/sddmm.ll
      ConfigPath: benchmarks/AD/sddmm/hw/sddmm.ini
      Debug: False
      PIOSize: 10
      PIOMaster: LocalBus
    - Var:
      - Name: MAT
        Type: SPM
        Size: 800000
        Ports: 2
    - Var:
      - Name: VEC
        Type: SPM
        Size: 800
        Ports: 2
    - Var:
      - Name: OUT
        Type: SPM
        Size: 1000
        Ports: 2
hw_config:
  top:
  sddmm:
