---
acc_cluster:
  - Name: matd2_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/sys_validation/matd2/hw/top.ll
      ConfigPath: benchmarks/sys_validation/matd2/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: matd2
      IrPath: benchmarks/sys_validation/matd2/hw/matd2.ll
      ConfigPath: benchmarks/sys_validation/matd2/hw/matd2.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: MAT
        Type: SPM
        Size: 80000
        Ports: 100
    - Var:
      - Name: VEC
        Type: SPM
        Size: 80000
        Ports: 100
    - Var:
      - Name: OUT
        Type: SPM
        Size: 80000
        Ports: 2