---
acc_cluster:
  - Name: gemm_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/AD/gemm/hw/top.ll
      ConfigPath: benchmarks/AD/gemm/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: gemm
      IrPath: benchmarks/AD/gemm/hw/gemm.ll
      ConfigPath: benchmarks/AD/gemm/hw/gemm.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
