---
acc_cluster:
  - Name: jacobi_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/sys_validation/jacobi/hw/top.ll
      ConfigPath: benchmarks/sys_validation/jacobi/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: jacobi
      IrPath: benchmarks/sys_validation/jacobi/hw/jacobi.ll
      ConfigPath: benchmarks/sys_validation/jacobi/hw/jacobi.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
